aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 315632178359.dkr.ecr.ap-south-1.amazonaws.com

docker build -f Dockerfile -t fse/stock-market .

docker tag fse/stock-market:latest 315632178359.dkr.ecr.ap-south-1.amazonaws.com/fse/stock-market:latest

docker push 315632178359.dkr.ecr.ap-south-1.amazonaws.com/fse/stock-market:latest